language: node_js
node_js:
  - "0.10"
services:
  - mongodb
  - redis-server
after_script:
  - npm run coveralls

env:
  global:
     secure: "VySvS5qxuWMZW0aG8auGEHZD899kWxbG9WZhGuH8IYkHpmz7rir1IgEfS4yPWDqanmgL9fWuV852UkG/GOHxZWtTdOt0xkbEMlHwz/1B8EK7WP2ZVtDSOkZoqsrmjmz7BxRXGiocgsK+V6hJ5BOyx/PncZKQb7WRdLowDQSDY4Y="
